# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import measurement_pb2 as measurement__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in measurement_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MeasurementServiceStub(object):
    """The LabVIEW Measurement Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/measurement.MeasurementService/GetStatus',
                request_serializer=measurement__pb2.StatusRequest.SerializeToString,
                response_deserializer=measurement__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.AcquireSensorData = channel.unary_unary(
                '/measurement.MeasurementService/AcquireSensorData',
                request_serializer=measurement__pb2.DataRequest.SerializeToString,
                response_deserializer=measurement__pb2.DataResponse.FromString,
                _registered_method=True)
        self.ProcessData = channel.unary_unary(
                '/measurement.MeasurementService/ProcessData',
                request_serializer=measurement__pb2.ProcessRequest.SerializeToString,
                response_deserializer=measurement__pb2.ProcessResponse.FromString,
                _registered_method=True)
        self.StreamSensorData = channel.unary_stream(
                '/measurement.MeasurementService/StreamSensorData',
                request_serializer=measurement__pb2.StreamRequest.SerializeToString,
                response_deserializer=measurement__pb2.DataPoint.FromString,
                _registered_method=True)


class MeasurementServiceServicer(object):
    """The LabVIEW Measurement Service
    """

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcquireSensorData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSensorData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeasurementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=measurement__pb2.StatusRequest.FromString,
                    response_serializer=measurement__pb2.StatusResponse.SerializeToString,
            ),
            'AcquireSensorData': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireSensorData,
                    request_deserializer=measurement__pb2.DataRequest.FromString,
                    response_serializer=measurement__pb2.DataResponse.SerializeToString,
            ),
            'ProcessData': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessData,
                    request_deserializer=measurement__pb2.ProcessRequest.FromString,
                    response_serializer=measurement__pb2.ProcessResponse.SerializeToString,
            ),
            'StreamSensorData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSensorData,
                    request_deserializer=measurement__pb2.StreamRequest.FromString,
                    response_serializer=measurement__pb2.DataPoint.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'measurement.MeasurementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('measurement.MeasurementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeasurementService(object):
    """The LabVIEW Measurement Service
    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/measurement.MeasurementService/GetStatus',
            measurement__pb2.StatusRequest.SerializeToString,
            measurement__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcquireSensorData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/measurement.MeasurementService/AcquireSensorData',
            measurement__pb2.DataRequest.SerializeToString,
            measurement__pb2.DataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/measurement.MeasurementService/ProcessData',
            measurement__pb2.ProcessRequest.SerializeToString,
            measurement__pb2.ProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSensorData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/measurement.MeasurementService/StreamSensorData',
            measurement__pb2.StreamRequest.SerializeToString,
            measurement__pb2.DataPoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
