# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: measurement.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'measurement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11measurement.proto\x12\x0bmeasurement\"\x0f\n\rStatusRequest\"6\n\x0eStatusResponse\x12\x13\n\x0bserver_time\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"#\n\x0b\x44\x61taRequest\x12\x14\n\x0csample_count\x18\x01 \x01(\x05\"\x1e\n\x0c\x44\x61taResponse\x12\x0e\n\x06values\x18\x01 \x03(\x01\"&\n\x0eProcessRequest\x12\x14\n\x0cinput_values\x18\x01 \x03(\x01\"/\n\x0fProcessResponse\x12\x0b\n\x03rms\x18\x01 \x01(\x01\x12\x0f\n\x07\x61verage\x18\x02 \x01(\x01\"$\n\rStreamRequest\x12\x13\n\x0binterval_ms\x18\x01 \x01(\x05\"-\n\tDataPoint\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x32\xb8\x02\n\x12MeasurementService\x12\x44\n\tGetStatus\x12\x1a.measurement.StatusRequest\x1a\x1b.measurement.StatusResponse\x12H\n\x11\x41\x63quireSensorData\x12\x18.measurement.DataRequest\x1a\x19.measurement.DataResponse\x12H\n\x0bProcessData\x12\x1b.measurement.ProcessRequest\x1a\x1c.measurement.ProcessResponse\x12H\n\x10StreamSensorData\x12\x1a.measurement.StreamRequest\x1a\x16.measurement.DataPoint0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'measurement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSREQUEST']._serialized_start=34
  _globals['_STATUSREQUEST']._serialized_end=49
  _globals['_STATUSRESPONSE']._serialized_start=51
  _globals['_STATUSRESPONSE']._serialized_end=105
  _globals['_DATAREQUEST']._serialized_start=107
  _globals['_DATAREQUEST']._serialized_end=142
  _globals['_DATARESPONSE']._serialized_start=144
  _globals['_DATARESPONSE']._serialized_end=174
  _globals['_PROCESSREQUEST']._serialized_start=176
  _globals['_PROCESSREQUEST']._serialized_end=214
  _globals['_PROCESSRESPONSE']._serialized_start=216
  _globals['_PROCESSRESPONSE']._serialized_end=263
  _globals['_STREAMREQUEST']._serialized_start=265
  _globals['_STREAMREQUEST']._serialized_end=301
  _globals['_DATAPOINT']._serialized_start=303
  _globals['_DATAPOINT']._serialized_end=348
  _globals['_MEASUREMENTSERVICE']._serialized_start=351
  _globals['_MEASUREMENTSERVICE']._serialized_end=663
# @@protoc_insertion_point(module_scope)
